### ISSUE TITLE
raise Exception("Read %s has none or more than 2 clusters" % read)

### ISSUE THREAD

**Issue by yuntwang** [cytham/nanovar#13]
@cytham 
Hi，recent I use nanovar detect SV,
the command line as follows:
**nanovar -x ont -t 10 -l 50  N01.bam sequences_new.fa N01**
An error occurred after a while:
nv_cov_upper.py:132: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_yticklabels(['{:,.1%}'.format(x) for x in vals])
Traceback (most recent call last):
  File "/share/nas1/zhiyq/scripts/anaconda3/envs/nanovar/bin/nanovar", line 479, in <module>
    main()
  File "/share/nas1/zhiyq/scripts/anaconda3/envs/nanovar/bin/nanovar", line 307, in main
    run.cluster_extract()
  File "/share/nas1/zhiyq/scripts/anaconda3/envs/nanovar/lib/python3.7/site-packages/nanovar/nv_characterize.py", line 95, in cluster_extract
    self.contig, False, self.seed2)
  File "/share/nas1/zhiyq/scripts/anaconda3/envs/nanovar/lib/python3.7/site-packages/nanovar/nv_cluster.py", line 53, in sv_cluster
    mincov,
  File "/share/nas1/zhiyq/scripts/anaconda3/envs/nanovar/lib/python3.7/site-packages/nanovar/nv_cluster.py", line 166, in rangecollect
    classdict, ins_switch, mincov, infodict)
  File "/share/nas1/zhiyq/scripts/anaconda3/envs/nanovar/lib/python3.7/site-packages/nanovar/nv_cluster.py", line 270, in cluster
    raise Exception("Read %s has none or more than 2 clusters" % read)
Exception: Read f1eb5b88-2771-4daa-bdbf-a9177b2e26a4~DBC65 has none or more than 2 clusters
/opt/gridengine/default/spool/hpc02-c-0-141/job_scripts/7442838: line 1: 13810 Segmentation fault      (core dumped) 

How can I deal with it.
Hope to get your reply.

**Comment by cytham** [comment]
Hi @yuntwang,

There seems to be an anomaly in the SV breakend clustering step. Do you mind running nanovar with the ```--debug``` option and send me the "subdata.tsv" and "parse1.tsv" files? The files might be too big to transfer over Github, thus you may want to share them over email or something else. My email is e0054302@u.nus.edu.

**Comment by yuntwang** [comment]
@cytham 
Sent mail, please check.
thanks

**Comment by cytham** [comment]
@yuntwang Thanks for the files

I could not replicate the error using the files, they ran fine without raising any exception. The data is quite large and I realized you had the "Segmentation fault (core dumped)" error at the end which might indicate a memory issue. Your system might have run out of memory at the clustering step. I had roughly calculated that the clustering step for your data may take up about 15 GB of RAM. Can you try running again with a larger allocation of memory? Thanks

**Comment by yuntwang** [comment]
@cytham  
ok, I try it.

**Comment by cytham** [comment]
@yuntwang managed to resolve the problem?

**Comment by cytham** [comment]
I assume the problem is resolved. Feel free to open this issue again.
