### ISSUE TITLE
"Exeption: Read has none or more than 2 clusters" error

### ISSUE THREAD

**Issue by kristinastenlokk** [cytham/nanovar#25]
Hi!

I have sucessfully been running NanoVar (v 1.3.8) for a number of identically processed nanpore samples, but I get the following error for one of them: 

[07/05/2021 08:16:12] - NanoVar started

Traceback (most recent call last):
  File "/mnt/users/kristenl/.conda/envs/py2.7/bin/nanovar", line 479, in <module>
    main()
  File "/mnt/users/kristenl/.conda/envs/py2.7/bin/nanovar", line 339, in main
    run.cluster_nn(add_out=sub_run.total_out)
  File "/mnt/users/kristenl/.conda/envs/py2.7/lib/python3.7/site-packages/nanovar/nv_characterize.py", line 124, in cluster_nn
    self.seed2)
  File "/mnt/users/kristenl/.conda/envs/py2.7/lib/python3.7/site-packages/nanovar/nv_cluster.py", line 53, in sv_cluster
    mincov,
  File "/mnt/users/kristenl/.conda/envs/py2.7/lib/python3.7/site-packages/nanovar/nv_cluster.py", line 166, in rangecollect
    classdict, ins_switch, mincov, infodict)
  File "/mnt/users/kristenl/.conda/envs/py2.7/lib/python3.7/site-packages/nanovar/nv_cluster.py", line 270, in cluster
    raise Exception("Read %s has none or more than 2 clusters" % read)
Exception: Read a224ebf9-06f8-48de-a8f2-8166ae626cec~HKN8Q has none or more than 2 clusters

My input is a bam-file created by Winnowmap2 + the reference (nanovar -t 10 alignment.bam reference.fa out). I have checked that there are no duplicated reads (by read name). I have also tried simply removing the reported read from the bam-file and re-running NanoVar, but the same error with a new read name was produced. Do you have any ideas to what could be happening here? Please let me know if there is any more information I should provide.

Thanks,
Kristina Stenløkk

**Comment by cytham** [comment]
Hi @kristinastenlokk, it might be caused by an index duplication bug in v1.3.8. Can you try with v1.3.9 and see if the error persists?
Sorry for the inconvenience.

**Comment by kristinastenlokk** [comment]
Hi again!

I am having some trouble installing/updating the latest version with conda (conda install -c bioconda nanovar). This worked fine for 1.3.8, so I'm wondering if it could be a problem with nanovar 1.3.9. I am getting this error: 

Solving environment: failed

InvalidVersionSpecError: Invalid version spec: =2.7

**Comment by cytham** [comment]
Hi, i think that is a problem with Conda. What version of Conda are you using? and can you try updating it? Thanks

**Comment by kristinastenlokk** [comment]
Sorry for the late reply! It was a conda problem, just like you said. NanoVar is running smoothly now. Thanks a lot!
