### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Tintest** [cytham/nanovar#6]
Hello,

I got an issue quite similar to #4 :

```
[06/02/2020 14:23:44] - INFO - Initialize NanoVar log file
[06/02/2020 14:23:44] - INFO - Version: NanoVar-1.2.7
[06/02/2020 14:23:44] - INFO - Command: /home/tintest/miniconda3/bin/nanovar -t 32 fastq/GM24385_all_30X_1.fastq REF/hg19.fasta /bettik/tintest/SV/nanopore/GIAB_bis/vcf/nanovar/30X_1/
[06/02/2020 14:38:57] - DEBUG - Input FASTQ/FASTA file passed
[06/02/2020 14:38:57] - INFO - Reads: fastq/GM24385_all_30X_1.fastq
[06/02/2020 14:38:57] - INFO - Reference genome: REF/hg19.fasta
[06/02/2020 14:38:57] - INFO - Working directory: /bettik/tintest/SV/nanopore/GIAB_bis/vcf/nanovar/30X_1/
[06/02/2020 14:38:57] - INFO - Filter file: None
[06/02/2020 14:38:57] - INFO - Minimum number of reads for calling a breakend: 1
[06/02/2020 14:38:57] - INFO - Minimum SV len: 25
[06/02/2020 14:38:57] - INFO - Mapping percent for split-read: 0.05
[06/02/2020 14:38:57] - INFO - Length buffer for clustering: 50
[06/02/2020 14:38:57] - INFO - Score threshold: 1.0
[06/02/2020 14:38:57] - INFO - Homozygous read ratio threshold: 0.75
[06/02/2020 14:38:57] - INFO - Heterozygous read ratio threshold: 0.35
[06/02/2020 14:38:57] - INFO - Number of threads: 32

[06/02/2020 14:38:57] - INFO - Total number of reads in FASTQ/FASTA: 12944486

[06/02/2020 14:38:57] - INFO - NanoVar started
[06/02/2020 14:39:23] - DEBUG - Make blast index skipped
[06/02/2020 14:39:23] - INFO - Windowmasker counts
[06/02/2020 14:39:24] - DEBUG - computing the genome length
[06/02/2020 14:39:26] - DEBUG - pass 1
[06/02/2020 14:50:53] - DEBUG - pass 2
[06/02/2020 15:01:13] - INFO - Windowmasker binary
[06/02/2020 15:01:13] - DEBUG - reading counts...
[06/02/2020 15:01:23] - DEBUG - converting counts...
[06/02/2020 15:02:07] - DEBUG - converting parameters...
[06/02/2020 15:02:07] - DEBUG - final processing...
[06/02/2020 15:02:07] - DEBUG - optimizing the data structure
[06/02/2020 15:02:11] - DEBUG - Make hs-blastn FMD-index skipped
[06/02/2020 15:02:11] - INFO - hs-blastn alignment
[06/02/2020 15:02:12] - DEBUG - [HS-BLASTN] Loading database.
[06/02/2020 15:02:12] - DEBUG - Loading REF/hg19.fasta.sequence, size = 3GB
[06/02/2020 15:02:16] - DEBUG - Loading REF/hg19.fasta.bwt, size = 3GB
[06/02/2020 15:02:21] - DEBUG - Loading REF/hg19.fasta.sa, size = 6GB
[06/02/2020 15:02:43] - DEBUG - [HS-BLASTN] done. Time elapsed: 30.70 secs.
[06/02/2020 15:02:43] - DEBUG - [HS-BLASTN] Processing /dev/fd/63.
[06/02/2020 15:02:54] - DEBUG - Processing 137878 queries.
[06/02/2020 15:07:41] - DEBUG - Processing 140350 queries.
[06/02/2020 15:12:52] - DEBUG - Processing 148731 queries.
[06/02/2020 15:17:25] - DEBUG - Processing 136794 queries.
[06/02/2020 15:21:57] - DEBUG - Processing 136603 queries.
[06/02/2020 15:26:18] - DEBUG - Processing 135209 queries.
[06/02/2020 15:30:32] - DEBUG - Processing 137844 queries.
[06/02/2020 15:34:59] - DEBUG - Processing 132154 queries.
[06/02/2020 15:39:38] - DEBUG - Processing 132103 queries.
[06/02/2020 15:45:04] - DEBUG - Processing 131202 queries.
[06/02/2020 15:49:37] - DEBUG - Processing 136384 queries.
[06/02/2020 15:54:15] - DEBUG - Processing 133643 queries.
[06/02/2020 15:59:01] - DEBUG - Processing 129906 queries.
[06/02/2020 16:03:16] - DEBUG - Processing 133765 queries.
[06/02/2020 16:07:41] - DEBUG - Processing 154417 queries.
[06/02/2020 16:12:31] - DEBUG - Processing 163421 queries.
[06/02/2020 16:16:45] - DEBUG - Processing 160525 queries.
[06/02/2020 16:21:21] - DEBUG - Processing 163702 queries.
[06/02/2020 16:25:47] - DEBUG - Processing 155458 queries.
[06/02/2020 16:30:05] - DEBUG - Processing 150965 queries.
[06/02/2020 16:34:22] - DEBUG - Processing 159268 queries.
[06/02/2020 16:38:39] - DEBUG - Processing 153957 queries.
[06/02/2020 16:43:17] - DEBUG - Processing 149643 queries.
[06/02/2020 16:47:35] - DEBUG - Processing 154179 queries.
[06/02/2020 16:52:23] - DEBUG - Processing 151804 queries.
[06/02/2020 16:56:59] - DEBUG - Processing 146948 queries.
[06/02/2020 17:01:30] - DEBUG - Processing 156913 queries.
[06/02/2020 17:05:57] - DEBUG - Processing 143785 queries.
[06/02/2020 17:10:37] - DEBUG - Processing 118549 queries.
[06/02/2020 17:15:03] - DEBUG - Processing 126584 queries.
[06/02/2020 17:19:22] - DEBUG - Processing 124894 queries.
[06/02/2020 17:23:45] - DEBUG - Processing 112584 queries.
[06/02/2020 17:28:00] - DEBUG - Processing 117480 queries.
[06/02/2020 17:32:25] - DEBUG - Processing 116210 queries.
[06/02/2020 17:36:45] - DEBUG - Processing 114259 queries.
[06/02/2020 17:41:17] - DEBUG - Processing 118698 queries.
[06/02/2020 17:45:40] - DEBUG - Processing 114442 queries.
[06/02/2020 17:50:10] - DEBUG - Processing 109940 queries.
[06/02/2020 17:54:30] - DEBUG - Processing 118745 queries.
[06/02/2020 17:58:41] - DEBUG - Processing 117530 queries.
[06/02/2020 18:02:54] - DEBUG - Processing 114855 queries.
[06/02/2020 18:07:26] - DEBUG - Processing 119438 queries.
[06/02/2020 18:12:15] - DEBUG - Processing 118689 queries.
[06/02/2020 18:16:41] - DEBUG - Processing 117488 queries.
[06/02/2020 18:20:38] - DEBUG - Processing 112254 queries.
[06/02/2020 18:24:42] - DEBUG - Processing 121578 queries.
[06/02/2020 18:29:09] - DEBUG - Processing 113593 queries.
[06/02/2020 18:33:35] - DEBUG - Processing 152951 queries.
[06/02/2020 18:38:00] - DEBUG - Processing 191235 queries.
[06/02/2020 18:43:18] - DEBUG - Processing 190922 queries.
[06/02/2020 18:46:59] - DEBUG - Processing 193276 queries.
[06/02/2020 18:51:21] - DEBUG - Processing 188411 queries.
[06/02/2020 18:55:05] - DEBUG - Processing 183200 queries.
[06/02/2020 18:59:02] - DEBUG - Processing 202782 queries.
[06/02/2020 19:02:56] - DEBUG - Processing 206935 queries.
[06/02/2020 19:06:29] - DEBUG - Processing 201991 queries.
[06/02/2020 19:09:54] - DEBUG - Processing 191799 queries.
[06/02/2020 19:13:57] - DEBUG - Processing 205376 queries.
[06/02/2020 19:17:59] - DEBUG - Processing 203947 queries.
[06/02/2020 19:21:49] - DEBUG - Processing 206379 queries.
[06/02/2020 19:26:02] - DEBUG - Processing 203293 queries.
[06/02/2020 19:30:04] - DEBUG - Processing 209249 queries.
[06/02/2020 19:33:42] - DEBUG - Processing 204763 queries.
[06/02/2020 19:37:51] - DEBUG - Processing 248000 queries.
[06/02/2020 19:41:32] - DEBUG - Processing 248000 queries.
[06/02/2020 19:44:22] - DEBUG - Processing 248000 queries.
[06/02/2020 19:47:07] - DEBUG - Processing 243804 queries.
[06/02/2020 19:51:41] - DEBUG - Processing 146215 queries.
[06/02/2020 19:56:01] - DEBUG - Processing 146940 queries.
[06/02/2020 20:00:45] - DEBUG - Processing 140500 queries.
[06/02/2020 20:04:56] - DEBUG - Processing 137536 queries.
[06/02/2020 20:09:21] - DEBUG - Processing 149435 queries.
[06/02/2020 20:13:32] - DEBUG - Processing 139187 queries.
[06/02/2020 20:17:34] - DEBUG - Processing 134622 queries.
[06/02/2020 20:21:38] - DEBUG - Processing 140153 queries.
[06/02/2020 20:26:27] - DEBUG - Processing 144879 queries.
[06/02/2020 20:30:51] - DEBUG - Processing 150527 queries.
[06/02/2020 20:35:24] - DEBUG - Processing 134255 queries.
[06/02/2020 20:40:11] - DEBUG - Processing 149958 queries.
[06/02/2020 20:44:57] - DEBUG - Processing 150176 queries.
[06/02/2020 20:49:21] - DEBUG - Processing 142866 queries.
[06/02/2020 20:53:41] - DEBUG - Processing 146646 queries.
[06/02/2020 20:58:27] - DEBUG - Processing 141881 queries.
[06/02/2020 21:03:27] - DEBUG - Processing 143917 queries.
[06/02/2020 21:07:47] - DEBUG - Processing 85119 queries.
[06/02/2020 21:10:46] - DEBUG - [HS-BLASTN] done. Elpased time: 22083.1336 secs.
[06/02/2020 21:10:46] - DEBUG - [HS-BLASTN] 12944486 queries processed.
[06/02/2020 21:10:48] - DEBUG - [CMD] hs-blastn align -db REF/hg19.fasta -window_masker_db /bettik/tintest/SV/nanopore/GIAB_bis/vcf/nanovar/30X_1/hg19.counts.obinary -query /dev/fd/63 -out /bettik/tintest/SV/nanopore/GIAB_bis/vcf/nanovar/30X_1/GM24385_all_30X_1-hg19-blast.tab -outfmt 6 -num_threads 31 -max_target_seqs 3 -gapopen 0 -gapextend 4 -penalty -3 -reward 2
[06/02/2020 21:10:48] - INFO - Parsing and detecting SVs
[06/02/2020 21:11:26] - INFO - Gap dictionary not loaded.
[06/02/2020 21:46:58] - INFO - Genome size: 3095677412 bases
[06/02/2020 21:46:58] - INFO - Mapped bases: 91970512924 bases
[06/02/2020 21:46:58] - INFO - Depth of coverage: 29.71x
[06/02/2020 21:46:58] - INFO - Read overlap upper limit: 92.6
[06/02/2020 21:46:58] - INFO - Clustering SV breakends

Traceback (most recent call last):
  File "/home/tintest/miniconda3/bin/nanovar", line 199, in <module>
    main()
  File "/home/tintest/miniconda3/bin/nanovar", line 185, in main
    run.cluster_nn()
  File "/home/tintest/miniconda3/lib/python3.7/site-packages/nanovar/nv_characterize.py", line 120, in cluster_nn
    cluster_out = sv_cluster(self.total_subdata, self.total_out, self.buff, self.maxovl, self.mincov)
  File "/home/tintest/miniconda3/lib/python3.7/site-packages/nanovar/nv_cluster.py", line 37, in sv_cluster
    if line[3] != line[8]:
IndexError: list index out of range
```

[Here is the 100 firsts of my reads ](https://filesender.renater.fr/?s=download&token=33fc44a8-a398-85d5-de3a-f9ebf326f61c)

Nanovar has been installed thanks to conda.

Can you help me ?

Thank you, 

Regards.

**Comment by cytham** [comment]
Hi Tintest,

Sorry for the late reply. 

NanoVar has been updated to v1.3.0. I have tested your reads on this new version and it ran successfully. Please reinstall this new version and try running your data again.

Sorry again for the delay and thanks for trying out NanoVar. Let me know how it goes.

Best,
cy

**Comment by MaestSi** [comment]
Hi @cytham , I faced a similar error with version with v1.3.1. If version v1.3.2 fixes this, are you please going to update the conda version?
Thanks in advance,
Simone

**Comment by cytham** [comment]
Hi Simone,

I am not sure if the error you are facing will be solved in v1.3.2 which will be available by today. I would need more information like the exact error and log file to troubleshoot.

Thanks

Best,
cy

**Comment by MaestSi** [comment]
Hi, here is the log: 
[NanoVar-030320-1536.log](https://github.com/cytham/nanovar/files/4286327/NanoVar-030320-1536.log).
The error message I had is the following:

```
Traceback (most recent call last):
  File "/home/simone/miniconda3/envs/NanoVar_env/bin/nanovar", line 452, in <module>
    main()
  File "/home/simone/miniconda3/envs/NanoVar_env/bin/nanovar", line 269, in main
    run.bam_parse_detect()
  File "/home/simone/miniconda3/envs/NanoVar_env/lib/python3.6/site-packages/nanovar/nv_characterize.py", line 76, in bam_parse_detect
    self.filter)
  File "nanovar/nv_bam_parser.pyx", line 168, in nanovar.nv_bam_parser.bam_parse
  File "/home/simone/miniconda3/envs/NanoVar_env/lib/python3.6/site-packages/nanovar/nv_parser.py", line 211, in breakpoint_parser
    coord2 = int(out.split('\t')[6].split(' ')[1].split(',')[int(del_count - del_counter)].split(':')[1].split('-')[1])
IndexError: list index out of range
```

**Comment by cytham** [comment]
Hi Simone,

Thanks for the error output and log file.

I am not sure what is causing the error. Can you please use the "debug" version of NanoVar that I have just created in the "debug" branch and send me the "nanovar_debug.txt" file?

Here are the instructions to do it:
```
# 1. Activate your conda environment which you installed NanoVar-1.3.1.

# 2. git clone the debug branch 
git clone -b debug https://github.com/cytham/nanovar.git

# 3. Install the debug version
cd nanovar
pip install .
# Check version 
nanovar -v (output should be "1.3.2-debug")

# 4. Run the debug version with the BAM file created in your failed run
mkdir test
nanovar -t 24 -f hg38 /path/to/BAM Homo_sapiens_assembly38.fasta ./test
# The run should stop at "Analyzing read alignments and detecting SVs -"
```
Once the run has finished, check if there is anything written in the "nanovar_debug.txt" file. If there is, please send me this file.

Thanks

Best,
cy

**Comment by MaestSi** [comment]
Hi, here are the log: 
[nanovar_debug.txt](https://github.com/cytham/nanovar/files/4286963/nanovar_debug.txt)
and the error:

```
Checking integrity of input files -
Indexing genome and aligning reads -
Analyzing read alignments and detecting SVs -
Traceback (most recent call last):
  File "/home/simone/miniconda3/envs/NanoVar_env/bin/nanovar", line 457, in <module>
    main()
  File "/home/simone/miniconda3/envs/NanoVar_env/bin/nanovar", line 273, in main
    run.bam_parse_detect()
  File "/home/simone/miniconda3/envs/NanoVar_env/lib/python3.6/site-packages/nanovar/nv_characterize.py", line 76, in bam_parse_detect
    self.filter)
  File "nanovar/nv_bam_parser.pyx", line 168, in nanovar.nv_bam_parser.bam_parse
  File "/home/simone/miniconda3/envs/NanoVar_env/lib/python3.6/site-packages/nanovar/nv_parser.py", line 218, in breakpoint_parser
    uniqidx = bp_uname + '~' + str(chrom) + ':' + str(min(coord1, coord2)) + '-' + str(max(coord1, coord2))
UnboundLocalError: local variable 'coord2' referenced before assignment
```
Thanks,
Simone

**Comment by cytham** [comment]
Hi Simone,

Thanks for trying it out. 

I think the problem lies with your contigs in the reference genome having symbols such as ":" and "-" as seen in "HLA-DRB1*11:04:01" from the debug file. Removing these contigs from the reference genome should solve the issue.

Because you had an interrupted run the first round, please do run with --force the next time you run NanoVar for the same output directory. And I would also advise to use v1.3.2.

I am sorry for this inconvenience and will provide a rectification for this issue in the next update.

Thanks for raising this issue and do continue to feedback any problems.

Best,
cy

**Comment by MaestSi** [comment]
Hi, so basically I should remove the alternative haplotypes from the hg38 reference genome. Moreover, I don't think minimap2 handles those contigs in a proper way (as BWA would), so that would be an additional reason for removing them from the reference. So, if I understood correctly, NanoVar should be able to resume the run from where it failed, if specifying the --force flag?
Thanks, I'll let you know about the output of the program.
Simone

**Comment by cytham** [comment]
Hi Simone,

The point is to remove or rename any contig in the reference genome that has those symbols. You can check the genome.sizes file to see the names of all the contigs. I suppose only the >HLA contigs have symbols and have to be removed or renamed. You can still keep the  alternative haplotypes or UNKN contigs as they do not have the symbols. I am unsure about the differences minimap2 or BWA handles these contigs.

The --force flag is used to ensure that the generation of the blast indexes are regenerated properly in the event that it was corrupted due to the premature termination of the previous run. 

There are two ways to run NanoVar now: 1) Using your FASTQ reads for a full run or 2) Using the BAM file generated from the previous run to continue it off halfway.. Please use --force for both methods.

Hope this helps.

Best,
cy

**Comment by MaestSi** [comment]
Hi, I confirm that after removing all '*', ':' and '-' from chromosomes names, NanoVar v1.3.2 worked without any errors!
Thanks,
Simone

**Comment by cytham** [comment]
Hi Simone,

Thanks for getting back to me and glad that it solved the problem. 

Best,
cy
