### ISSUE TITLE
cytocad is not listed as a dependency for nanovar:1.5.0

### ISSUE THREAD

**Issue by GallVp** [cytham/nanovar#68]
Traceback (most recent call last):
    File "/usr/local/bin/nanovar", line 4, in <module>
      __import__('pkg_resources').run_script('nanovar==1.5.0', 'nanovar')
    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
      self.require(requires)[0].run_script(script_name, ns)
    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1448, in run_script
      exec(code, namespace, namespace)
    File "/usr/local/lib/python3.9/dist-packages/nanovar-1.5.0-py3.9-linux-x86_64.egg/EGG-INFO/scripts/nanovar", line 591, in <module>
      main()
    File "/usr/local/lib/python3.9/dist-packages/nanovar-1.5.0-py3.9-linux-x86_64.egg/EGG-INFO/scripts/nanovar", line 342, in main
      from nanovar.nv_characterize import VariantDetect
    File "/usr/local/lib/python3.9/dist-packages/nanovar-1.5.0-py3.9-linux-x86_64.egg/nanovar/nv_characterize.py", line 35, in <module>
      from cytocad.change_detection import cad
  ModuleNotFoundError: No module named 'cytocad'

**Comment by cytham** [comment]
Hi @GallVp, thanks for reporting this, I have pushed a quick fixed on Github, please try the latest version from the master branch. I will integrate the fix into a new release later.

**Comment by GallVp** [comment]
Thank you @cytham

 I have got it working with numpy==1.9.5 and tensorflow-cpu==2.5.0. Now I have run into a new problem. It says:


Traceback (most recent call last):
  File "/usr/local/bin/nanovar", line 4, in <module>
    __import__('pkg_resources').run_script('nanovar==1.5.0', 'nanovar')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/nanovar-1.5.0-py3.9-linux-x86_64.egg/EGG-INFO/scripts/nanovar", line 591, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/nanovar-1.5.0-py3.9-linux-x86_64.egg/EGG-INFO/scripts/nanovar", line 370, in main
    run.cluster_nn2()
  File "/usr/local/lib/python3.9/dist-packages/nanovar-1.5.0-py3.9-linux-x86_64.egg/nanovar/nv_characterize.py", line 113, in cluster_nn2
    self.out_nn = inference(cluster_out, self.total_out, self.model)
  File "/usr/local/lib/python3.9/dist-packages/nanovar-1.5.0-py3.9-linux-x86_64.egg/nanovar/nv_nn.py", line 48, in inference
    finalp = finalprob(i.split('\t')[8], i.split('\t')[11], probdict)
  File "/usr/local/lib/python3.9/dist-packages/nanovar-1.5.0-py3.9-linux-x86_64.egg/nanovar/nv_nn.py", line 226, in finalprob
    prob += float(probdict[i])
KeyError: 'c1h3fh_10979917-29cf-f9c6-6818-5def13db60c3|chr1_1_21898217'


But this c1h3fh_10979917-29cf-f9c6-6818-5def13db60c3|chr1_1_21898217 is present in detect.tsv.

**Comment by GallVp** [comment]
Would access to my dataset help? What's the best way to share data? The reference FASTA is 38 MB and the BAM is 700 MBs.

**Comment by cytham** [comment]
Yes, that would be great, will you be able to upload to google drive or dropbox?

**Comment by cytham** [comment]
Closed due to inactivity.
