### ISSUE TITLE
Missing AS tag

### ISSUE THREAD

**Issue by kcleal** [cytham/nanovar#93]
Hi,

Im trying to process a sample that seems to lack AS tags. I run in to this error:

```
  Traceback (most recent call last):
    File "/media/kez/9377f7a6-1ddc-488c-be9f-946154c35bd1/public_genomes/SV_Benchmark_CMRG/work/conda/env-35e4fa79218de400-2f314976d50375c19e686e85ef4338fb/bin/nanovar", line 10, in <module>
      sys.exit(main())
               ^^^^^^
    File "/media/kez/9377f7a6-1ddc-488c-be9f-946154c35bd1/public_genomes/SV_Benchmark_CMRG/work/conda/env-35e4fa79218de400-2f314976d50375c19e686e85ef4338fb/lib/python3.11/site-packages/nanovar/nanovar.py", line 334, in main
      run.bam_parse_detect()
    File "/media/kez/9377f7a6-1ddc-488c-be9f-946154c35bd1/public_genomes/SV_Benchmark_CMRG/work/conda/env-35e4fa79218de400-2f314976d50375c19e686e85ef4338fb/lib/python3.11/site-packages/nanovar/nv_characterize.py", line 83, in bam_parse_detect
      = bam_parse(self.sam, self.minlen, self.splitpct, self.minalign, self.dir, self.filter, self.contig_omit)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "nv_bam_parser.pyx", line 80, in nanovar.nv_bam_parser.bam_parse
    File "pysam/libcalignedsegment.pyx", line 2507, in pysam.libcalignedsegment.AlignedSegment.get_tag
    File "pysam/libcalignedsegment.pyx", line 2546, in pysam.libcalignedsegment.AlignedSegment.get_tag
  KeyError: "tag 'AS' not present"
```

The sample can be found online here:

https://downloads.pacbcloud.com/public/2024Q4/Vega/HG002/Human-WGS-variant-pipeline/HiFi-human-WGS-WDL_v2.0.0-rc4/

Filename  is:

    m21009_241011_231051.GRCh38.haplotagged.bam
        
    
Also does nanovar work with cram files?

Thanks!

**Comment by cytham** [comment]
Hi @kcleal, it looks like your BAM file does not have AS tags. The current NanoVar version does not support BAMs without AS tag. You will need to realign your reads using an aligner that produces AS tag, such as minimap2.
NanoVar does support CRAM files.

**Comment by YihangLin123** [comment]
Hello! Would you be interested in updating the NanoVar version to support BAM files without AS tags?
