### ISSUE TITLE
ModuleNotFoundError: No module named 'nanovar.nv_bam_parser'

### ISSUE THREAD

**Issue by 0Bernhard** [cytham/nanovar#94]
Dear nanovar team

I get following error message and i am not sure how to solve it. could you please advise? Thank you. 

nanovar ~/Documents/analysis_20240929/SQK-NBD114-24_barcode03.fastq ~/Documents/analysis_20
240929/CP018074_chrm.fasta ~/Documents/analysis_20240929/nanovar/barcode3
[01/12/2024 15:05:02] - NanoVar started
Checking integrity of input files -
Indexing genome and aligning reads -
Analyzing read alignments and detecting SVs -
Traceback (most recent call last):
  File "/home/administrator/miniconda3/envs/nanovar/bin/nanovar", line 452, in <module>
    main()
  File "/home/administrator/miniconda3/envs/nanovar/bin/nanovar", line 264, in main
    from nanovar.nv_characterize import VariantDetect
  File "/home/administrator/miniconda3/envs/nanovar/lib/python3.11/site-packages/nanovar/nv_characterize.py", line 26, in <module>
    from nanovar.nv_bam_parser import bam_parse
ModuleNotFoundError: No module named 'nanovar.nv_bam_parser'

**Comment by 0Bernhard** [comment]
I managed after a fresh install and downgrading tensorflow as in previous issue. This issue is therefore closed.
